### ISSUE TITLE
Heterodyne example not working

### ISSUE THREAD

**Issue by HaiwenWang** [qutip/qutip#1029]
I am trying to implement this heterodyne example provided here:
https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/smesolve-heterodyne.ipynb

It seems that the main issue is that this example is written in an old version and the **general_stochastic** function is not supported any more. So I changed to **smesolve** and modified its arguments, which leads me to the following code (which still doesn't work):

```python
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
from qutip import *
from qutip.expect import expect_rho_vec

N = 15
w0 = 1.0 * 2 * np.pi
A = 0.1 * 2 * np.pi
times = np.linspace(0, 15, 301)
gamma = 0.25

ntraj = 150
nsubsteps = 50

a = destroy(N)
x = a + a.dag()
y = -1.0j*(a - a.dag())

H = w0 * a.dag() * a + A * (a + a.dag())

rho0 = coherent(N, np.sqrt(5.0), method='analytic')
c_ops = [np.sqrt(gamma) * a]
e_ops = [a.dag() * a, x, y]
m_ops=[x, y]

result_ref = mesolve(H, rho0, times, c_ops, e_ops)
#plot_expectation_values(result_ref)
#plt.show()

L = liouvillian(H)
D = lindblad_dissipator(c_ops[0])
d1_operator = L + D
def d1_rho_func(t, rho_vec):
    return d1_operator * rho_vec

B1 = spre(c_ops[0]) + spost(c_ops[0].dag())
B2 = spre(c_ops[0]) + spost(c_ops[0].dag())
def d2_rho_func(t, rho_vec):
    e1 = expect_rho_vec(B1.data, rho_vec, False)
    drho1 = B1 * rho_vec - e1 * rho_vec

    e1 = expect_rho_vec(B2.data, rho_vec, False)
    drho2 = B2 * rho_vec - e1 * rho_vec

    return np.vstack([1.0/np.sqrt(2) * drho1, -1.0j/np.sqrt(2) * drho2])
# Everything above is almost the same as the example. I only modified the following part
result = smesolve(H=H*0, rho0=ket2dm(rho0), times=times,
                  e_ops=e_ops,
                  d1=d1_rho_func, d2=d2_rho_func,
                  d2_len=2, ntraj=ntraj, nsubsteps=nsubsteps*2,
                  dW_factors=[np.sqrt(2/gamma), np.sqrt(2/gamma)],
                  store_measurement=True, map_func=parallel_map)
```

The error message
```
============================= test session starts ==============================
platform darwin -- Python 3.6.8, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /Users/haiwen/PycharmProjects/Qutip_test, inifile:Total run time:   0.13s

test_smesolve2.py:None (test_smesolve2.py)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/haiwen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/haiwen/anaconda3/lib/python3.6/site-packages/qutip/stochastic.py", line 1040, in _smesolve_single_trajectory
    A_ops, dt, dW[:, t_idx, j, :], d1, d2, sso.args)
  File "/Users/haiwen/anaconda3/lib/python3.6/site-packages/qutip/stochastic.py", line 1789, in _rhs_rho_euler_maruyama
    dW_len = len(dW[0, :])
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:
test_smesolve2.py:53: in <module>
    store_measurement=True, map_func=parallel_map)
../../anaconda3/lib/python3.6/site-packages/qutip/stochastic.py:593: in smesolve
    res = _smesolve_generic(sso, sso.options, sso.progress_bar)
../../anaconda3/lib/python3.6/site-packages/qutip/stochastic.py:936: in _smesolve_generic
    task_args, task_kwargs, **map_kwargs)
../../anaconda3/lib/python3.6/site-packages/qutip/parallel.py:260: in parallel_map
    return [ar.get() for ar in async_res]
../../anaconda3/lib/python3.6/site-packages/qutip/parallel.py:260: in <listcomp>
    return [ar.get() for ar in async_res]
../../anaconda3/lib/python3.6/multiprocessing/pool.py:644: in get
    raise self._value
E   IndexError: index 0 is out of bounds for axis 0 with size 0
collected 0 items / 1 errors
==================================== ERRORS ====================================
______________________ ERROR collecting test_smesolve2.py ______________________
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/haiwen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/haiwen/anaconda3/lib/python3.6/site-packages/qutip/stochastic.py", line 1040, in _smesolve_single_trajectory
    A_ops, dt, dW[:, t_idx, j, :], d1, d2, sso.args)
  File "/Users/haiwen/anaconda3/lib/python3.6/site-packages/qutip/stochastic.py", line 1789, in _rhs_rho_euler_maruyama
    dW_len = len(dW[0, :])
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:
test_smesolve2.py:53: in <module>
    store_measurement=True, map_func=parallel_map)
../../anaconda3/lib/python3.6/site-packages/qutip/stochastic.py:593: in smesolve
    res = _smesolve_generic(sso, sso.options, sso.progress_bar)
../../anaconda3/lib/python3.6/site-packages/qutip/stochastic.py:936: in _smesolve_generic
    task_args, task_kwargs, **map_kwargs)
../../anaconda3/lib/python3.6/site-packages/qutip/parallel.py:260: in parallel_map
    return [ar.get() for ar in async_res]
../../anaconda3/lib/python3.6/site-packages/qutip/parallel.py:260: in <listcomp>
    return [ar.get() for ar in async_res]
../../anaconda3/lib/python3.6/multiprocessing/pool.py:644: in get
    raise self._value
E   IndexError: index 0 is out of bounds for axis 0 with size 0
------------------------------- Captured stdout --------------------------------
Total run time:   0.13s
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.92 seconds ============================
Process finished with exit code 0
```

Does anyone have suggestions on what is going wrong here? Thanks a lot!

**Comment by nathanshammah** [comment]
Please refer to [`smesolve` new methods](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolver-new-methods.ipynb) and [benchmark](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-smesolve-tests.ipynb). I think you should just use `c_ops` or `sc_ops`. Keeping this open as the notebook needs to be updated and the Users guide documentation. The [API documentation](http://qutip.org/docs/latest/apidoc/functions.html?highlight=smesolve#qutip.stochastic.smesolve) is updated.

**Comment by HaiwenWang** [comment]
Thanks for the reply, and the new example. Passing sc_ops to smesolve does work.

**Comment by hodgestar** [comment]
The heterodyne stochastic example was updated as part of this year's GSoC tutorial renovation project. The updated notebook can be found at https://nbviewer.org/urls/qutip.org/qutip-tutorials/tutorials-v4/time-evolution/015_smesolve-heterodyne.ipynb.

Thank you for reporting this.
