### ISSUE TITLE
the inverse of an operator

### ISSUE THREAD

**Issue by HAyAsIiI** [qutip/qutip#1102]
I tried to calculate the inverse of an operator as following:
```
>>> import qutip as qt
>>> from scipy.sparse.linalg import inv
>>> inv(qt.sigmaz().data)
C:\Users\username\Miniconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:296: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\username\Miniconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:203: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  'is in the CSC matrix format', SparseEfficiencyWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\Miniconda3\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 78, in inv       
    Ainv = spsolve(A, I)
  File "C:\Users\username\Miniconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 223, in spsolve
    shape=b.shape, dtype=A.dtype)
  File "C:\Users\username\Miniconda3\lib\site-packages\qutip\fastsparse.py", line 59, in __init__
    if args[1].shape[0] and args[1].dtype != np.int32:
AttributeError: 'tuple' object has no attribute 'shape'
```
I don't know why this doesn't work.
Although I can convert it to be dense, and use `scipy.linalg.inv` to do the same job,
the super operaters to be inverted in my actual problems are extremely large and sparse, and the inverses are also expected to be sparse.
So I want to find a way without converting them to dense.
But I didn't find any function in QuTiP to do that. Or maybe I missed it?

BTW, the version I use is:
```
QuTiP Version:      4.4.1
Numpy Version:      1.16.5
Scipy Version:      1.3.1
Cython Version:     0.29.13
Matplotlib Version: 3.1.1
Python Version:     3.7.3
Number of CPUs:     4
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\username\Miniconda3\lib\site-packages\qutip
```

**Comment by tehruhn** [comment]
Hi @HAyAsIiI ,
would you consider doing the following?

```
import qutip as qt
from scipy.sparse.linalg import inv
import numpy as np
from scipy import sparse

sMat = sparse.csr_matrix(np.asarray(qt.sigmaz( )))
```

Since a few version back, when we've added a __array__ method to Qobj. So now you can have sMat be your sparse matrix.
