### ISSUE TITLE
Error in importing

### ISSUE THREAD

**Issue by PiggsBoson** [qutip/qutip#1119]
When I was trying to run a script written with qutip on a cluster with Ubunt 18.04, python 2.7 conda 4.7.12 installed, the following error occurred.

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    from qutip import *
  File "/home/user/miniconda2/lib/python2.7/site-packages/qutip/__init__.py", line 171, in <module>
    from qutip.qobj import *
  File "/home/user/miniconda2/lib/python2.7/site-packages/qutip/qobj.py", line 2434, in <module>
    import qutip.superop_reps as sr
  File "/home/user/miniconda2/lib/python2.7/site-packages/qutip/superop_reps.py", line 61, in <module>
    from qutip.superoperator import vec2mat, spre, spost, operator_to_vector
  File "/home/user/miniconda2/lib/python2.7/site-packages/qutip/superoperator.py", line 408, in <module>
    from qutip.qobjevo import QobjEvo
  File "/home/user/miniconda2/lib/python2.7/site-packages/qutip/qobjevo.py", line 515
    raise TypeError("Qobj not compatible.") from e

**Comment by Freakwill** [comment]
I think you should use python3.
