### ISSUE TITLE
'Error calculating H' when trying to use mcsolve() for time-dependent Hamiltonians

### ISSUE THREAD

**Issue by abdurakhimov** [qutip/qutip#1368]
I am trying to run this code to test mcsolve():
```
import numpy as np
from qutip import *

def hamiltonian_t(t, args):
    #
    # evaluate the hamiltonian at time t. 
    #
    H0 = args['H0']
    H1 = args['H1']
    w = args['w']

    return H0 + H1 * np.sin(w*t)

N = 2 # set where to truncate Fock state for cavity
a = destroy(N)
psi0 = basis(N, 0) # define initial state

w_c = 1.0 * 2 * np.pi  # cavity frequency
w  = w_c
kappa = 0.001 * 2 * np.pi

H0 = w_c * a.dag()*a   # time-independent term
H1 = kappa*(a.dag() + a)  # time-dependent term

c_ops = []  # Build collapse operators
c_ops.append(np.sqrt(kappa) * a)

args = {'H0': H0, 'H1': H1, 'w': w}

times = np.linspace(0, 10, 100) # define time vector

output = mcsolve(hamiltonian_t, psi0, times, c_ops, [a.dag()*a], args=args)
```

I am getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/qutip/mcsolve.py", line 365, in run_test
    rhs, ode_args = self.ss.makefunc(ss)
NameError: name 'ss' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mc_solve_example2.py", line 33, in <module>
    output = mcsolve(hamiltonian_t, psi0, times, c_ops, [a.dag()*a], args=args)
  File "/usr/local/lib64/python3.6/site-packages/qutip/mcsolve.py", line 223, in mcsolve
    mc.run_test()
  File "/usr/local/lib64/python3.6/site-packages/qutip/mcsolve.py", line 368, in run_test
    raise Exception("Error calculating H")
Exception: Error calculating H
```

Here is the output of qutip.about()
```
QuTiP Version:      4.5.1
Numpy Version:      1.18.4
Scipy Version:      1.4.1
Cython Version:     0.29.19
Matplotlib Version: 3.2.1
Python Version:     3.6.8
Number of CPUs:     112
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

Any advice how to fix that?

**Comment by Ericgig** [comment]
List format time dependant Hamiltonian:
```
def f(t, args):
    return np.sin(args['w']*t)

H = [H0, [H1, f]]
```
would give the same Hamiltonian and work with `mcsolve`.
