### ISSUE TITLE
AttributeError: 'float' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Rahulquantum** [qutip/qutip#1386]
**While using Qutip Latest version on Spyder with these imports:** 
from qutip import *
from scipy import *
import os.path
import numpy as np
import matplotlib.pylab as plt
import os

**I got the following error while calculating f_modes and f_energies"**

`Traceback (most recent call last):

  File "/media/rahul/DATA/IISER-PUNE-2019/MBL_copy_30-10-2020/MBL/new_codes/CDT.py", line 121, in <module>
    f_modes_0, f_energies = floquet_modes(H, T, args, True)

  File "/home/rahul/anaconda3/lib/python3.8/site-packages/qutip/floquet.py", line 102, in floquet_modes
    U = propagator(H, T, [], args)

  File "/home/rahul/anaconda3/lib/python3.8/site-packages/qutip/propagator.py", line 184, in propagator
    output = sesolve(H2, psi0, tlist, [],

  File "/home/rahul/anaconda3/lib/python3.8/site-packages/qutip/sesolve.py", line 157, in sesolve
    ss = _sesolve_QobjEvo(H, tlist, args, options)

  File "/home/rahul/anaconda3/lib/python3.8/site-packages/qutip/sesolve.py", line 185, in _sesolve_QobjEvo
    H_td = -1.0j * QobjEvo(H, args, tlist=tlist)

  File "/home/rahul/anaconda3/lib/python3.8/site-packages/qutip/qobjevo.py", line 467, in __init__
    self.args = args.copy()

**AttributeError: 'float' object has no attribute 'copy'`**

Earlier in my previous system with older version of qutip and python this used to work fine

**Comment by BoxiLi** [comment]
Could you also post your full code? In particular, your definition of `args` in
```
f_modes_0, f_energies = floquet_modes(H, T, args, True)
```
 It seems that you defined it as a float number, but it should be a dictionary.

**Comment by Rahulquantum** [comment]
You are correct, I defined it as a float omega, I redefined it as
args={'w',omega} and change my Hamiltonian as:
H=[[H0,'sin(w*t)']]
Then it ran successfully. Thankyou So much!
In previous qutip version it somehow worked with float when I defined as:
args=omega
H = [Qobj(H0), [H1, lambda t, w: sin(w*t)]]
