### ISSUE TITLE
Incompatible large enough dimensions for initial state and c_ops in mesolve gives segfault

### ISSUE THREAD

**Issue by caryan** [qutip/qutip#1456]
Passing incompatible dimensions for `rho0`, `H` and `c_ops` to `mesolve` leads to a segfault when the dimensions are large enough and when passing `c_ops`. 

**To Reproduce**

Pass something for the initial state that is neither a state vector nor square density matrix.

```python
from qutip import *

D = 13
psi0 = tensor(coherent(D, 100e-9), qeye(D))
result = mesolve(qeye(D**2), psi0,[0, 100e-9], [destroy(D**2)])```
```
```
(qutip) ➜  ~ python mwe.py 
[1]    83143 segmentation fault  python mwe.py
```

Changing `D = 13` to `D = 12` correctly raises a `ValueError`:
```
(qutip) ➜  ~ python mwe.py
Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    result = mesolve(qeye(D**2), psi0,[0, 100e-9], [destroy(D**2)])
  File "/Users/colmrya/miniconda3/envs/qutip/lib/python3.8/site-packages/qutip/mesolve.py", line 266, in mesolve
    func(0., v, *ode_args) + v
ValueError: operands could not be broadcast together with shapes (20736,) (1728,) 
```

Trying to get a little more info on the segfault:

```
(qutip) ➜  ~ lldb --file python mwe.py
(lldb) target create "/Users/colmrya/miniconda3/envs/qutip/bin/python"
Current executable set to '/Users/colmrya/miniconda3/envs/qutip/bin/python' (x86_64).
(lldb) settings set -- target.run-args  "mwe.py"
(lldb) r
Process 83317 launched: '/Users/colmrya/miniconda3/envs/qutip/bin/python' (x86_64)
Process 83317 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1168d1000)
    frame #0: 0x0000000113018acd spmatfuncs.cpython-38-darwin.so`__pyx_f_5qutip_2cy_10spmatfuncs_spmvpy(std::__1::complex<double>*, int*, int*, std::__1::complex<double>*, std::__1::complex<double>, std::__1::complex<double>*, unsigned int) + 157
spmatfuncs.cpython-38-darwin.so`__pyx_f_5qutip_2cy_10spmatfuncs_spmvpy:
->  0x113018acd <+157>: movupd (%rcx,%rax), %xmm4
    0x113018ad2 <+162>: mulpd  %xmm4, %xmm3
    0x113018ad6 <+166>: movddup (%rbx), %xmm5             ; xmm5 = mem[0,0] 
    0x113018ada <+170>: shufpd $0x1, %xmm4, %xmm4        ; xmm4 = xmm4[1,0] 
Target 0: (python) stopped.
```

Not passing `c_ops` restores just raising a `ValueError`

```python
from qutip import *

D = 13
psi0 = tensor(coherent(D, 100e-9), qeye(D))
result = mesolve(qeye(D**2), psi0,[0, 100e-9], [])
```
gives
```
 (qutip) ➜  ~ python mwe.py            
Traceback (most recent call last):
  File "mwe.py", line 5, in <module>
    result = mesolve(qeye(D**2), psi0,[0, 100e-9], [])
  File "/Users/colmrya/miniconda3/envs/qutip/lib/python3.8/site-packages/qutip/mesolve.py", line 266, in mesolve
    func(0., v, *ode_args) + v
ValueError: operands could not be broadcast together with shapes (28561,) (2197,) 
```

**Expected behavior**
A exception for incompatible dimensions raised in all cases.

** Environment**
Please use `qutip.about()` to get the information about your environment and paste it here.

```
(qutip) ➜  ~ ipython
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import qutip
q
In [2]: qutip.about()

QuTiP: Quantum Toolbox in Python
================================
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li and Jake Lishman.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.5.3
Numpy Version:      1.19.2
Scipy Version:      1.6.1
Cython Version:     0.29.22
Matplotlib Version: 3.3.4
Python Version:     3.8.8
Number of CPUs:     6
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
Installation path:  /Users/colmrya/miniconda3/envs/qutip/lib/python3.8/site-packages/qutip
================================================================================
Please cite QuTiP in your publication.
================================================================================
For your convenience a bibtex reference can be easily generated using `qutip.cite()`

```

**Comment by jakelishman** [comment]
Ah, nice catch thanks, and thanks for the super clear repro.

We're overhauling the solvers for QuTiP 5.0, which will include a lot more rigorous input checking on entry, but also it uses far safer low-level datatypes  that would catch this shape mismatch in the C layer (even though the `dims` _should_ have been checked by `mesolve`).  I'll check the other solvers and patch in a sanity test - probably after these lines: https://github.com/qutip/qutip/blob/d5e305513d9186df74beee4fd8da680e89f29d15/qutip/mesolve.py#L259-L261
we can just insert a test
```python
    if rho0.dims[0] != rho0.dims[1]:
        raise ValueError(
            "input state must be a pure state or square density matrix"
        )
```

There may also be other segfaults lurking if you use a Python function to generate a time-dependent `Qobj` value in the Liouvillian or the expectation operators, but right now you're unlikely to use that form (because it's slow as anything).

The bug slips through because we unsafely pass off a matrix down to C code (where we currently don't have sanity checks) without first verifying that it is a valid shape in Python space - the C code is working as designed, so there shouldn't be problems with correct inputs.  Removing `c_ops` causes `mesolve` to delegate to `sesolve` which presumably is better at its type-checking, and I expect that a small dimension size working is likely just `malloc` having slack in the memory it gives us for small sizes or small requests being allocated into the special pre-allocated store.
