### ISSUE TITLE
DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by mba5811** [qutip/qutip#1613]
Hi friends,

I'm going to import qutip as 

from qutip import *

but i get this error:

Traceback (most recent call last):
  File "D:\py\Master_solve.py", line 4, in <module>
    import qutip
  File "C:\Users\Phd-02\AppData\Roaming\Python\Python36\site-packages\qutip\__init__.py", line 149, in <module>
    from qutip.qobj import *
  File "C:\Users\Phd-02\AppData\Roaming\Python\Python36\site-packages\qutip\qobj.py", line 60, in <module>
    from qutip.fastsparse import fast_csr_matrix, fast_identity
  File "C:\Users\Phd-02\AppData\Roaming\Python\Python36\site-packages\qutip\fastsparse.py", line 423, in <module>
    from qutip.cy.spmath import (zcsr_transpose, zcsr_adjoint, zcsr_mult)
ImportError: DLL load failed: The specified module could not be found.

Any suggestion?Thanks in advance.

**Comment by hodgestar** [comment]
@mba5811 Which version of QuTiP are you using?
