### ISSUE TITLE
No attribute 'blas_opt_info'

### ISSUE THREAD

**Issue by goerz** [qutip/qutip#1753]
### Bug Description

When trying to reproduce the [code for the quip-qip paper](https://github.com/boxili/qutip-qip-paper), I'm running into an
~~~
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'
~~~

The full stacktrace indicates that the problem is in the QuTiP code, so I'm reporting it here. Looks like https://github.com/qutip/qutip/issues/1750#issuecomment-1005876725 also ran into this

### Code to Reproduce the Bug

```shell
goerz@ophelia(r) main:~/Documents/qutipqip/> python3.8 -m venv venv
goerz@ophelia(r) main:~/Documents/qutipqip/qutip-qip> ../venv/bin/python -m pip install -e .[full]
goerz@ophelia(r) main:~/Documents/qutipqip/qutip-qip> ../venv/bin/python -m pip install joblib
goerz@ophelia(r) main:~/Documents/qutipqip/qutip-qip-paper> ../venv/bin/python dj_algorithm.py
```

### Code Output

```shell
Traceback (most recent call last):
  File "dj_algorithm.py", line 28, in <module>
    from qutip_qip.device import OptPulseProcessor, LinearSpinChain, SCQubits
  File "/Users/goerz/Documents/qutipqip/qutip-qip/src/qutip_qip/device/__init__.py", line 4, in <module>
    from .processor import Processor, Model
  File "/Users/goerz/Documents/qutipqip/qutip-qip/src/qutip_qip/device/processor.py", line 9, in <module>
    import qutip
  File "/Users/goerz/Documents/qutipqip/venv/lib/python3.8/site-packages/qutip/__init__.py", line 73, in <module>
    (_blas_info() == "OPENBLAS" and platform.system() == 'Darwin')
  File "/Users/goerz/Documents/qutipqip/venv/lib/python3.8/site-packages/qutip/utilities.py", line 430, in _blas_info
    blas_info = config.blas_opt_info
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'
```

### Expected Behaviour

It should run the example :-)

### Your Environment

```shell
goerz@ophelia(r) main:~/Documents/qutipqip/qutip-qip-paper> ../venv/bin/pip freeze
attrs==21.4.0
cycler==0.11.0
fonttools==4.28.5
iniconfig==1.1.1
joblib==1.1.0
kiwisolver==1.3.2
matplotlib==3.5.1
numpy==1.22.0
packaging==21.3
Pillow==9.0.0
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.6
pytest==6.2.5
python-dateutil==2.8.2
qutip==4.6.2
-e git+git@github.com:qutip/qutip-qip.git@04962ded1f6f21620f06f52869b61c4f392e9dea#egg=qutip_qip
scipy==1.7.3
six==1.16.0
toml==0.10.2
```

### Additional Context

`import qutip` (for `qutip.about()`) also triggers the backtrace

**Comment by AGaliciaMartinez** [comment]
Thank you for reporting this! It should be fixed once  PR #1752  gets merged.

**Comment by hodgestar** [comment]
I've merged #1752 and scheduled this for inclusion in the 4.6.3 release. Thank you again for reporting this @goerz!

**Comment by goerz** [comment]
👍 You guys are fast! 😄

**Comment by hodgestar** [comment]
*Sometimes* we are fast. :D
