### ISSUE TITLE
Add boundary condition options for spline based `QobjEvo`.

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2098]
### Problem Description

The choice of boundary condition for spline used in `QobjEvo` can have observable impact on the system, see #2063.
But `QobjEvo` can only use scipy default boundary condition.

### Proposed Solution

Add the `bc_type` keyword to `InterCoefficient` and `QobjEvo`. 
`coefficient` pass though `kwargs` from `QobjEvo` to `InterCoefficient`, but should be added to the doc-string.

**Comment by awkwardPotato812** [comment]
Hi Eric, I would like to work on this issue. Can you give me a bit more details on this?

**Comment by awkwardPotato812** [comment]
Hi Eric. Thanks for the info! So, I have gone over the code base and have identified the specific files that would be modified as a part of the change. I have listed them below:
- [QobjEvo.pyx](https://github.com/qutip/qutip/blob/master/qutip/core/cy/qobjevo.pyx) : Modify `__init__` and `read_element` methods to include `bc_type`
- [coefficient.py](https://github.com/qutip/qutip/blob/master/qutip/core/coefficient.py): Modify `coefficient` method to include `bc_type` in the arguments
- [coefficient.pyx](https://github.com/qutip/qutip/blob/master/qutip/core/cy/coefficient.pyx): Modify `InterCoefficient` to include `bc_type` and pass the argument to `make_interp_spline`

Let me know if I have missed out on anything else? 

Also, for the documentation changes, is there a specific example that needs to be specified? Or should I just specify details similar to the [Scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.make_interp_spline.html)?

**Comment by Ericgig** [comment]
The list look fine.
For the docstring, you can just refer the the scipy documentation and skip some of the details.

**Comment by awkwardPotato812** [comment]
Hi Eric,
   I've created a draft PR request for the changes. I did try to generate documentation according to the steps mentioned in the wiki but am faced with the following error:
```
 make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.5.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/User/miniconda3/envs/qutip-doc/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/home/User/miniconda3/envs/qutip-doc/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/User/Projects/QuantumStuff/qutip/doc/conf.py", line 95, in <module>
    _check_source_folder_and_imported_qutip_match()
  File "/home/User/Projects/QuantumStuff/qutip/doc/conf.py", line 80, in _check_source_folder_and_imported_qutip_match
    import qutip
  File "/home/User/Projects/QuantumStuff/qutip/qutip/__init__.py", line 34, in <module>
    from .core import *
  File "/home/User/Projects/QuantumStuff/qutip/qutip/core/__init__.py", line 2, in <module>
    from .coefficient import *
  File "/home/User/Projects/QuantumStuff/qutip/qutip/core/coefficient.py", line 24, in <module>
    from .data import Data
  File "/home/User/Projects/QuantumStuff/qutip/qutip/core/data/__init__.py", line 3, in <module>
    from . import dense, csr
  File "qutip/core/data/dense.pyx", line 1, in init qutip.core.data.dense
  File "qutip/core/data/csr.pyx", line 1, in init qutip.core.data.csr
  File "qutip/core/data/add.pyx", line 17, in init qutip.core.data.add
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```
Do you have any suggestions on how to address this?

**Comment by tamakoshi2001** [comment]
@awkwardPotato812 Hi. Your error is similar to the problem on this [website ](https://iq.opengenus.org/module-compiled-against-api-version-0x10-but-this-version-of-numpy-is-0xe/). You may have to upgrade your numpy.

**Comment by awkwardPotato812** [comment]
@tamakoshi2001 Thanks for the info! That fixed my error.
