### ISSUE TITLE
Use qutip core's `solve` instead of `_solve` in `qutip/solver/counstat.py`.

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip#2109]
### Describe the Issue!

In #2002, we added a function to solve `Ax=b` problems using qutip data object (`Qobj.data`).
`counstat` was done prior to that PR and has it's own [wrapper around scipy's functions](https://github.com/qutip/qutip/blob/c499d44ead02bd16861efa67c3e133cf3b7ed9e5/qutip/solver/countstat.py#L77). 
It should be changed to use [`qutip.core.data.solve`](https://github.com/qutip/qutip/blob/c499d44ead02bd16861efa67c3e133cf3b7ed9e5/qutip/core/data/solve.py#L169).

Ideally, we should add the capacity to pass options to this solver:
- `countstat_current_noise(.., method="direct", solve_opt={})`
- `_data.solve(A, b, solve_opt.pop("method", None), solve_opt)` <- name collision on `method`.

**Comment by hodgestar** [comment]
> Hello. I am interested in this issue. Can I try this?

Yes, please go ahead and ask questions if needed.

**Comment by tamakoshi2001** [comment]
I am going to change [this line](https://github.com/qutip/qutip/blob/c499d44ead02bd16861efa67c3e133cf3b7ed9e5/qutip/solver/countstat.py#L77) because this is the only line that uses [wrapper around scipy's functions](https://github.com/qutip/qutip/blob/c499d44ead02bd16861efa67c3e133cf3b7ed9e5/qutip/solver/countstat.py#L77) and delete the wrapper. Is this a good idea?

**Comment by tamakoshi2001** [comment]
I first changed scipy to _data.solve() in the _solve() and tried to see if this works well by pytest. I encountered the error below. Could you tell me how to fix this or another way to test the change? I do not know where is qutip.version.

ImportError while loading conftest '/root/opt/qutip/qutip/tests/conftest.py'.
__init__.py:6: in <module>
    import qutip.version
E   ModuleNotFoundError: No module named 'qutip.version'

**Comment by tamakoshi2001** [comment]
Hi. I replaced scipy wrapper with _data.solve. I ran pytest and error occurred. Does anybody know how to solve this? Thank you.

  File "qutip/core/data/dispatch.pyx", line 582, in qutip.core.data.dispatch.Dispatcher.__call__
    raise TypeError("unknown types to dispatch on: " + str(dispatch)) from None
TypeError: unknown types to dispatch on: [<class 'scipy.sparse._csr.csr_matrix'>, <class 'numpy.ndarray'>]
Traceback (most recent call last):
  File "/root/opt/qutip/qutip/solver/countstat.py", line 83, in _solve
    return _data.solve(A, V, "splu")

**Comment by tamakoshi2001** [comment]
@hodgestar Thank you for your reply. I added `_data.Dense(V)`, but failed. The first code failed and the second code passed the test.
```
def _solve(A, V):
    try:
        if settings.has_mkl:
            return _data.solve(A, V, "mkl_spsolve", {"csc": True})
        else:
            return _data.solve(A, V, "splu")
    except TypeError:
        out = _data.solve(A,_data.Dense(V))
    return out
```
```
def _solve(A, V):
    try:
        if settings.has_mkl:
            return _data.solve(A, V, "mkl_spsolve", {"csc": True})
        else:
            return _data.solve(A, V, "splu")
    except TypeError:
        out = sp.linalg.lsqr(A, V)[0]
    return out
```

**Comment by tamakoshi2001** [comment]
Hi. By clarifying the data types `_data.solve(_data.CSR(A),_data.Dense(V))`, Typeerror stops, but Attribute error occurred instead.
`E   AttributeError: 'qutip.core.data.dense.Dense' object has no attribute 'ndim'`

**Comment by Ericgig** [comment]
Hi @tamakoshi2001,
The whole function `_solve(A, V)` should be replaced by a call to `_data.solve`.
It is used only once at line 116, and the input are `CSR` and `Dense` object converted to scipy and numpy classes for this one call. You can just remove the conversions and replace the function.

**Comment by tamakoshi2001** [comment]
@Ericgig Hi. I thought the same thing and changed like this `X_rho = [_data.dense.fast_from_numpy(_data.solve(A, op))`. However, pytest failed and outputs TypeError. I tried to fix it by specifying the data types;` _data.CSR(A), _data.Dense(op)` and AttributeError happens in this case.

**Comment by Ericgig** [comment]
The input are originally already `_data.Data` object (`CSR` or `Dense`), for the `_solve` call, we transform them to numpy/ scipy object and then transform them back to `_data.Data`.  To make this work, you need to remove unneeded transformation in both direction.
