### ISSUE TITLE
IndexError in eigs_csr

### ISSUE THREAD

**Issue by Sola85** [qutip/qutip#2584]
### Bug Description

When orthogonalizing eigenvectors of degenerate eigenvalues, an IndexError can occur if the tolerance for detecting degenerate eigenvalues is too small.
In the below example, the eigenvalues are (excluding degeneracies) `[0, 1, 2, 3, 4-1e-13, 4, 5, 6]`. 

Degeneracy is currently determined by https://github.com/qutip/qutip/blob/359cbf777e38d06dd973ec69d1c9dec91c496dcd/qutip/core/data/eigen.py#L243

If `evals[i] == 4-1e-13`, then 4-1e-13 and 4 are considered **non-degenerate**, but when `evals[i] == 4`, then 4-1e-13 and 4 are considered **degenerate**. This messes up the logic that comes afterwards.

### Code to Reproduce the Bug

```shell
import qutip

N: qutip.Qobj = sum(qutip.expand_operator((1+qutip.sigmaz())/2, [2]*6, i) for i in range(6)) 

qutip.simdiag((N, N))
```

### Code Output

```shell
Traceback (most recent call last):
  File ".../qutip_debugging.py", line 5, in <module>
    qutip.simdiag((N, N))
  File ".../python3.9/site-packages/qutip/simdiag.py", line 93, in simdiag
    eigvals, eigvecs = _data.eigs(ops[0].data, True, True)
  File "qutip/core/data/dispatch.pyx", line 392, in qutip.core.data.dispatch.Dispatcher.__call__
  File ".../python3.9/site-packages/qutip/core/data/eigen.py", line 260, in eigs_csr
    _orthogonalize(evecs[:, i+l], evecs[:, i+k])
IndexError: index 64 is out of bounds for axis 1 with size 64
```

### Expected Behaviour

One way of fixing this would be by only counting degenerate eigenvalues that are strictly larger than or equal to the eigenvalue currently under consideration, i.e. replacing the line above by `num_degen = np.sum(np.abs(evals[i:] - evals[i]) < (2 * tol or 1e-14))` (notice the `evals[i:]`).
Then 4-1e-13 and 4 would be truly considered as separate, and orthonormalization would only occur within each eigenspace.

A different option might be to use this error to warn the user that the tolerance might be too low. E.g.
```python
if i+num_degen >= len(evals):
    raise Exception("Orthogonalizing degenerate eigenspaces failed. Try lowering the tolerance.")
```

Another related problem:
I found this issue not by calling eigs directy but by using simdiag. But I dont think the `tol` parameter of simdiag gets passed into `eigs_csr` and hence is not used in the critical line and hence `tol=0` and cannot be changed in this case. So this bug cannot be circumvented without modifying qutip source when using simdiag.

### Your Environment

```shell
QuTiP Version:      5.0.4
Numpy Version:      1.26.4
Scipy Version:      1.12.0
Cython Version:     0.29.28
Matplotlib Version: 3.5.1
Python Version:     3.9.12
Number of CPUs:     24
BLAS Info:          Generic
INTEL MKL Ext:      False
Platform Info:      Linux (x86_64)
```

**Comment by Sola85** [comment]
Thanks for the fix!
