### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by dberma15** [qutip/qutip#343]
Hi,

I'm having some trouble installing QuTiP onto my computer. I'm running Python 2.7 on Windows 7 and using Anaconda 2.10 64 bit and PyCharm 4.0.4.
I tried installing QuTiP in PyCharm by using file->settings->project interpreter and that successfully installed. However, when I go to the python console and type
from qutip import * I get the following error message:

Backend Qt4Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Users\daniel\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-674d9281af88>", line 1, in <module>
    from qutip import *
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\__init__.py", line 213, in <module>
    from qutip.qobj import *
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\qobj.py", line 60, in <module>
    from qutip.ptrace import _ptrace
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\ptrace.py", line 38, in <module>
    from qutip.sparse import sp_reshape
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\sparse.py", line 49, in <module>
    from qutip.cy.sparse_utils import (_sparse_profile, _sparse_permute,
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\cy\__init__.py", line 1, in <module>
    from qutip.cy.spmatfuncs import *
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\pyximport\pyximport.py", line 431, in load_module
    language_level=self.language_level)
  File "C:\Users\daniel\Anaconda\lib\site-packages\pyximport\pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "C:\Users\daniel\Anaconda\lib\site-packages\pyximport\pyximport.py", line 186, in build_module
    reload_support=pyxargs.reload_support)
  File "C:\Users\daniel\Anaconda\lib\site-packages\pyximport\pyxbuild.py", line 98, in pyx_to_dll
    dist.run_commands()
  File "C:\Users\daniel\Anaconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\daniel\Anaconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\daniel\Anaconda\lib\site-packages\Cython\Distutils\build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\daniel\Anaconda\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\Users\daniel\Anaconda\lib\site-packages\Cython\Distutils\build_ext.py", line 171, in build_extensions
    self.build_extension(ext)
  File "C:\Users\daniel\Anaconda\lib\distutils\command\build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "C:\Users\daniel\Anaconda\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Users\daniel\Anaconda\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Users\daniel\Anaconda\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module qutip.cy.spmatfuncs failed: ['DistutilsPlatformError: Unable to find vcvarsall.bat\n']

I tried testing to see if it was installed correctly by typing import qutip.testing as qt and I get

Traceback (most recent call last):
  File "C:\Users\daniel\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-ae6395ba7937>", line 1, in <module>
    import qutip.testing as qt
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\daniel\Anaconda\lib\site-packages\qutip\__init__.py", line 62, in <module>
    qutip.settings.ipython = False
AttributeError: 'module' object has no attribute 'settings'

I have also tried downloading the file, putting it in the folder Anaconda\pkgs, opening a command window, setting the path and installing it there. I don't get any error messages but I still cannot seem to import QuTiP. What am I doing wrong?

**Comment by nonhermitian** [comment]
Did you add

[build]
compiler = mingw32

[build_ext]
compiler = mingw32

to the Anaconda distutils.cfg file?
