### ISSUE TITLE
Wrong import order in setup.py

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip#426]
Hi,

I think the import order is not correct in `setup.py`, importing `numpy` at the beginning of the file, before giving a chance to `setuptools` to actually install it (because it is in required packages). This line is faulty https://github.com/qutip/qutip/blob/master/setup.py#L34 and results in

``` zsh
% pip install qutip
Collecting qutip
  Downloading qutip-3.1.0.tar.gz (800kB)
    100% |████████████████████████████████| 802kB 595kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w53v9c3b/qutip/setup.py", line 34, in <module>
        import numpy as np
    ImportError: No module named 'numpy'
```

Then, instead of `pip install qutip`, one has to `pip install numpy; pip install qutip`.

**Comment by Phyks** [comment]
Note that the same holds for Cython:

```zsh
% pip install qutip
Collecting qutip
  Using cached qutip-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hg437fn6/qutip/setup.py", line 159, in <module>
        configuration=configuration
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-hg437fn6/qutip/setup.py", line 135, in configuration
        config.add_subpackage('qutip')
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "qutip/setup.py", line 8, in configuration
        config.add_subpackage('cy')
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 883, in _get_configuration_from_setup_py
        ('.py', 'U', 1))
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/home/phyks/.local/share/virtualenvs/physique/lib/python3.5/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "qutip/cy/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'
    Installing without the fortran mcsolver.
```

**Comment by nonhermitian** [comment]
This does look like an issue.  Will look into it.

**Comment by nonhermitian** [comment]
This has been dealt with.

**Comment by Phyks** [comment]
Thanks!
