### ISSUE TITLE
version 3.2.0 can not run self testing. OSX system

### ISSUE THREAD

**Issue by phyliu79** [qutip/qutip#445]
1. version 3.2.0 can not run testing in my mac system OS X EI Capitan. When I try:
`$  python3 -c "import qutip.testing as qt; qt.run()"`
I get the follow message:
> ----------------------------------------------------------------------
> Ran 0 tests in 0.000s

2. However, the testing.py and the folder 'tests' exist. I can run the test in the 'tests' folder one-by-one. For example, when I run:
`$ sudo python3  test_mesolve.py`
I get
> .....................
> Ran 21 tests in 48.167s
>
> OK
3. `sudo` is needed here for permission. For example, when I run: 
 `$ python3  test_mesolve.py`
I get a set of the following error message

>  .....E...E.E...E..E..
> ======================================================================
> ERROR: mesolve: time-dependence as array with super as init cond
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qutip-3.2.0.dev0-py3.5-macosx-10.6-intel.egg/qutip/tests/test_mesolve.py", line 638, in testMETDDecayAsArray
>     out1 = mesolve(H, psi0, tlist, c_op_list, [])
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qutip-3.2.0.dev0-py3.5-macosx-10.6-intel.egg/qutip/mesolve.py", line 277, in mesolve
>     progress_bar)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qutip-3.2.0.dev0-py3.5-macosx-10.6-intel.egg/qutip/mesolve.py", line 661, in _mesolve_list_str_td
>     cgen.generate(config.tdname + ".pyx")
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qutip-3.2.0.dev0-py3.5-macosx-10.6-intel.egg/qutip/cy/codegen.py", line 116, in generate
>     self.file(filename)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/qutip-3.2.0.dev0-py3.5-macosx-10.6-intel.egg/qutip/cy/codegen.py", line 78, in file
>     self.file = open(filename, "w")
> PermissionError: [Errno 13] Permission denied: 'rhs165050.pyx'

**Comment by phyliu79** [comment]
The problem is solved by myself. This is due to remain files after I  uninstalling qutip 3.1.0. One 
just need to delete the whole folder 'lib.macosx-10.11-x86_64-3.5' at the position ~/.pyxbld. Then the self testing working.
