### ISSUE TITLE
Unreliable correlation tests

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#607]
Some correlation tests fail on some attempts.
Not really clear why.
This issue can be used to keep a record, and then they can be fixed.

This is an example:
```
======================================================================
FAIL: correlation: comparing me and mc for driven oscillator in fock state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/qutip-4.1.0.dev0+0e91439-py2.7-linux-x86_64.egg/qutip/tests/test_correlation.py", line 125, in test_compare_solvers_coherent_state_memc
    assert_(abs(corr1 - corr2).max() < 0.2)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/numpy/testing/utils.py", line 77, in assert_
    raise AssertionError(smsg)
AssertionError
```

**Comment by ajgpitch** [comment]
resolved by #605
