### ISSUE TITLE
Unreliable tests

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#621]
Some tests fail from time to time. Most likely they need to have their tolerances increased
This issue replaces #607 as it is more general

**Comment by ajgpitch** [comment]
This is one example:
```
======================================================================
FAIL: correlation: comparing me and mc for driven oscillator in fock state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/qutip-4.1.0.dev0+0e91439-py2.7-linux-x86_64.egg/qutip/tests/test_correlation.py", line 125, in test_compare_solvers_coherent_state_memc
    assert_(abs(corr1 - corr2).max() < 0.2)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/numpy/testing/utils.py", line 77, in assert_
    raise AssertionError(smsg)
AssertionError
```

**Comment by ajgpitch** [comment]
Here is another:
```
======================================================================
FAIL: Superoperator: Convert superoperator to Choi matrix and back.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/qutip-4.0.3-py3.5-linux-x86_64.egg/qutip/tests/test_superop_reps.py", line 111, in test_ChoiKrausChoi
    assert_((test_choi - choi_matrix).norm() < tol)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/numpy/testing/utils.py", line 77, in assert_
    raise AssertionError(smsg)
AssertionError
```

**Comment by nonhermitian** [comment]
Will address today.

**Comment by nonhermitian** [comment]
Will address other test errors as they pop up.
