### ISSUE TITLE
Test missing for floquet_master_equation_tensor

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#624]
qutip-doc/guide/scripts/floquet_ex3.py raises an exception in `floquet_master_equation_tensor`
```
TypeError: Qobj data must be in fast_csr format.
```
This should have been picked up by a test.

**Comment by ajgpitch** [comment]
Tests didn't catch this one either:
```
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/qutip-dev-py3/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "<string>", line 28, in <module>
  File "/home/alex/GitHub/qutip/qutip/floquet.py", line 973, in fmmesolve
    floquet_basis=floquet_basis)
  File "/home/alex/GitHub/qutip/qutip/floquet.py", line 836, in floquet_markov_mesolve
    rho.data = vec2mat(r.y)
  File "/home/alex/GitHub/qutip/qutip/qobj.py", line 328, in set_data
    raise TypeError('Qobj data must be in fast_csr format.')
TypeError: Qobj data must be in fast_csr format.
```

**Comment by sahmed95** [comment]
You can use [coverage](http://www.saltycrane.com/blog/2012/04/test-coverage-nose-and-coveragepy/) with nose to see which part of the code is not getting caught by the tests. I have the coverage report for floquet here : http://sahmed.in/qutip_cover/qutip_floquet_py.html

This can be quite useful at times.

**Comment by hodgestar** [comment]
The equivalent functionality has tests in version 5.
