### ISSUE TITLE
Issue with me/mcsolve safety checkes

### ISSUE THREAD

**Issue by kafischer** [qutip/qutip#630]
The checks are too restrictive. For the collapse and expectation operator lists, previous versions allowed the input of single operators. The documentation also explicitly states this is OK.

Ex.  
mesolve(qzero(2), fock(2, 1), [0, 2], destroy(2), sigmaz())

But now this yields the error:

Traceback (most recent call last):
  File "/home/kevinf/PycharmProjects/QutipProjects/test/test.py", line 3, in <module>
    mesolve(qzero(2), fock(2, 1), [0, 2], destroy(2), sigmaz())
  File "/usr/local/lib/python3.4/dist-packages/qutip/mesolve.py", line 208, in mesolve
    _solver_safety_check(H, rho0, c_ops, e_ops, args)
  File "/usr/local/lib/python3.4/dist-packages/qutip/solver.py", line 813, in _solver_safety_check
    for ii in range(len(c_ops)):
TypeError: object of type 'Qobj' has no len()

**Comment by nonhermitian** [comment]
It is not so much the safety checks as the order in which a simple single operator is converted internally to a list vs. when the safety checks are run.  This is fixed in #631.
