### ISSUE TITLE
Callback functions in mesolve

### ISSUE THREAD

**Issue by WolfgangLechner** [qutip/qutip#645]
To reproduce the problem:

- run Lecture 8 - Adiabatic sweep from qutip lectures with qutip 4.02

- Error message:

Traceback (most recent call last):
  File "as.py", line 92, in <module>
    mesolve(h_t, psi0, taulist, [], process_rho, args)
  File "/usr/local/lib/python2.7/site-packages/qutip/mesolve.py", line 208, in mesolve
    _solver_safety_check(H, rho0, c_ops, e_ops, args)
  File "/usr/local/lib/python2.7/site-packages/qutip/solver.py", line 822, in _solver_safety_check
    for ii in range(len(e_ops)):
TypeError: object of type 'function' has no len()

**Comment by nonhermitian** [comment]
Update to 4.1 dev or do [e_ops].

-P

**Comment by WolfgangLechner** [comment]
Thanks!
