### ISSUE TITLE
Errors in installation verifying process

### ISSUE THREAD

**Issue by qingfengshi** [qutip/qutip#788]
I am trying to install qutip 3.1.0 on my MS Windows following the official steps:
1. Install the Python(X,Y) distribution (tested with version 2.7.3.1). Other Python distributions, such as Enthought Python Distribution or Anaconda CE have also been reported to work.
2. When installing Python(x,y), explicitly select to include the Cython package in the installation. This package is not selected by default.
3. Add the following content to the file C:/Python27/Lib/distutils/distutils.cfg (or create the file if it does not already exists):
[build]
compiler = mingw32
[build_ext]
compiler = mingw32
The directory where the distutils.cfg file should be placed might be different if you have installed the Python environment in a different location than in the example above.
4. Obtain the QuTiP source code and installed it following the instructions given above.

However, there are some errors after i run the installation verifying process. Is there anyone came across such errors? How can I repair these errors? The errors are presented as follow:
======================================================================
ERROR: qutip.tests.test_stochastic_me.test_ssesolve_photocurrent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_me.py", line 60, in test_ssesolve_photocurrent
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 527, in smesolve
    res = _smesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 870, in _smesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   3.46s. Est. time left: 00:00:00:25
20.0%. Run time:   4.37s. Est. time left: 00:00:00:17
32.0%. Run time:   5.00s. Est. time left: 00:00:00:10
40.0%. Run time:   5.01s. Est. time left: 00:00:00:07
52.0%. Run time:   5.65s. Est. time left: 00:00:00:05
60.0%. Run time:   5.69s. Est. time left: 00:00:00:03
72.0%. Run time:   6.31s. Est. time left: 00:00:00:02
80.0%. Run time:   6.89s. Est. time left: 00:00:00:01
Total run time:   7.03s

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: qutip.tests.test_stochastic_me.test_ssesolve_homodyne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_me.py", line 90, in test_ssesolve_homodyne
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 527, in smesolve
    res = _smesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 870, in _smesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   3.40s. Est. time left: 00:00:00:24
20.0%. Run time:   4.32s. Est. time left: 00:00:00:17
32.0%. Run time:   4.88s. Est. time left: 00:00:00:10
40.0%. Run time:   4.89s. Est. time left: 00:00:00:07
52.0%. Run time:   5.45s. Est. time left: 00:00:00:05
60.0%. Run time:   5.49s. Est. time left: 00:00:00:03
72.0%. Run time:   6.02s. Est. time left: 00:00:00:02
80.0%. Run time:   6.57s. Est. time left: 00:00:00:01
Total run time:   6.62s

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: qutip.tests.test_stochastic_me.test_ssesolve_heterodyne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_me.py", line 120, in test_ssesolve_heterodyne
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 527, in smesolve
    res = _smesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 870, in _smesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   4.13s. Est. time left: 00:00:00:30
20.0%. Run time:   5.12s. Est. time left: 00:00:00:20
32.0%. Run time:   6.16s. Est. time left: 00:00:00:13
40.0%. Run time:   6.21s. Est. time left: 00:00:00:09
52.0%. Run time:   7.26s. Est. time left: 00:00:00:06
60.0%. Run time:   7.37s. Est. time left: 00:00:00:04
72.0%. Run time:   8.34s. Est. time left: 00:00:00:03
80.0%. Run time:   9.25s. Est. time left: 00:00:00:02
Total run time:   9.33s

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: qutip.tests.test_stochastic_se.test_ssesolve_photocurrent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_se.py", line 59, in test_ssesolve_photocurrent
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 365, in ssesolve
    res = _ssesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 692, in _ssesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   3.30s. Est. time left: 00:00:00:24
20.0%. Run time:   4.23s. Est. time left: 00:00:00:16
32.0%. Run time:   4.61s. Est. time left: 00:00:00:09
40.0%. Run time:   4.61s. Est. time left: 00:00:00:06
52.0%. Run time:   4.99s. Est. time left: 00:00:00:04
60.0%. Run time:   5.01s. Est. time left: 00:00:00:03
72.0%. Run time:   5.37s. Est. time left: 00:00:00:02
80.0%. Run time:   5.74s. Est. time left: 00:00:00:01
Total run time:   5.89s

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: qutip.tests.test_stochastic_se.test_ssesolve_homodyne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_se.py", line 89, in test_ssesolve_homodyne
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 365, in ssesolve
    res = _ssesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 692, in _ssesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   3.31s. Est. time left: 00:00:00:24
20.0%. Run time:   4.25s. Est. time left: 00:00:00:16
32.0%. Run time:   4.65s. Est. time left: 00:00:00:09
40.0%. Run time:   4.65s. Est. time left: 00:00:00:06
52.0%. Run time:   5.06s. Est. time left: 00:00:00:04
60.0%. Run time:   5.07s. Est. time left: 00:00:00:03
72.0%. Run time:   5.50s. Est. time left: 00:00:00:02
80.0%. Run time:   5.88s. Est. time left: 00:00:00:01
Total run time:   5.99s

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: qutip.tests.test_stochastic_se.test_ssesolve_heterodyne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\qutip\tests\test_stochastic_se.py", line 119, in test_ssesolve_heterodyne
    map_func=parallel_map)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 365, in ssesolve
    res = _ssesolve_generic(sso, sso.options, sso.progress_bar)
  File "C:\Python27\lib\site-packages\qutip\stochastic.py", line 692, in _ssesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "C:\Python27\lib\site-packages\qutip\parallel.py", line 266, in parallel_map
    return [ar.get() for ar in async_res]
  File "C:\Python27\lib\multiprocessing\pool.py", line 554, in get
    raise self._value
ValueError: object of too small depth for desired array
-------------------- >> begin captured stdout << ---------------------
12.0%. Run time:   3.81s. Est. time left: 00:00:00:27
20.0%. Run time:   4.76s. Est. time left: 00:00:00:19
32.0%. Run time:   5.66s. Est. time left: 00:00:00:12
40.0%. Run time:   5.67s. Est. time left: 00:00:00:08
52.0%. Run time:   6.59s. Est. time left: 00:00:00:06
60.0%. Run time:   6.65s. Est. time left: 00:00:00:04
72.0%. Run time:   7.53s. Est. time left: 00:00:00:02
80.0%. Run time:   8.38s. Est. time left: 00:00:00:02
Total run time:   8.43s

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 320 tests in 1336.173s

FAILED (SKIP=7, errors=6)

**Comment by nonhermitian** [comment]
Should probably try QuTiP 4.2.

**Comment by qingfengshi** [comment]
OK, thank you for your reply.
I am just afraid that QuTip 4.2 can not be compatible with Pythonxy.
I will have a try.

**Comment by nonhermitian** [comment]
It probably won't work with pythonxy.  However, pythonxy is a dead project.
