### ISSUE TITLE
Problem when using MKL

### ISSUE THREAD

**Issue by ingstra** [qutip/qutip#791]
Hello! I'm trying to use the steadystate solver. When not using MKL, my program runs (albeit a bit slow). When using MKL, I get the following error message. I have tried to figure it out myself, to no avail.

Traceback (most recent call last):
  File "cubicH_quantumPump_loop.py", line 54, in <module>
    rho = steadystate(H, c_ops)
  File "/home/ingrid/anaconda3/lib/python3.6/site-packages/qutip/steadystate.py", line 234, in steadystate
    return _steadystate_direct_sparse(A, ss_args)
  File "/home/ingrid/anaconda3/lib/python3.6/site-packages/qutip/steadystate.py", line 400, in _steadystate_direct_sparse
    v = mkl_spsolve(L, b, perm = in_perm, verbose = ss_args['verbose'])
  File "/home/ingrid/anaconda3/lib/python3.6/site-packages/qutip/_mkl/spsolve.py", line 384, in mkl_spsolve
    x = lu.solve(b, verbose=verbose)
  File "/home/ingrid/anaconda3/lib/python3.6/site-packages/qutip/_mkl/spsolve.py", line 167, in solve
    raise Exception(pardiso_error_msgs[str(error)])
KeyError: '[-4]'

**Comment by nonhermitian** [comment]
You may want to try the development version.  However, it is saying that the MKL solver is failing with a zero pivot.  At present, it is not possible to modify the underlying parameters for the solver, but it is something I want to do.  The MKL solver is quite fast but sometimes runs into trouble.

**Comment by pranavm1502** [comment]
Hi! I am also facing the same problem  with steadystate solver. I am also unaware of how to "not use" MKL for the solver. Is there some settings which can be changed to turn it off?

**Comment by nonhermitian** [comment]
This should be addressed in Pull #801.  The only other reported instance of error when using the MKL solver was resolved when the new kwarg `weighted_matching=False` is used in the steady state solver.
