### ISSUE TITLE
matplotlib error while trying to do bloch.save()

### ISSUE THREAD

**Issue by tilek** [qutip/qutip#796]
Hi QuTip team and community! I just installed QuTiP on my Mac and I am very excited to try it out.

I started playing with this section of QuTiP User Guide [Plotting on the Bloch Sphere
](http://qutip.org/docs/4.1/guide/guide-bloch.html), but encountered an error.

This code works well if I run it in Python console:
```
from qutip import *
bloch = Bloch()
bloch.show()
```
But the following code in Python console shows an error
```
bloch.save()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/qutip/bloch.py", line 663, in save
    '.' + format)
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2188, in print_figure
    self.figure.dpi = dpi
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 436, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 745, in set_size_inches
    manager.resize(int(canvasw), int(canvash))
  File "/Users/tilek/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 540, in resize
    self.canvas._tkcanvas.master.geometry("%dx%d" % (width, height))
  File "/Users/tilek/miniconda2/lib/python2.7/lib-tk/Tkinter.py", line 1668, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
```

When I try to execute the code from the User Guide as a complete .py Python file (see below) 
it produces first bloch_0.png file where it is supposed to, but then shows the same error.
```
import numpy as np
from qutip import *
from scipy import *

def qubit_integrate(w, theta, gamma1, gamma2, psi0, tlist):
    # operators and the hamiltonian
    sx = sigmax(); sy = sigmay(); sz = sigmaz(); sm = sigmam()
    H = w * (cos(theta) * sz + sin(theta) * sx)
    # collapse operators
    c_op_list = []
    n_th = 0.5 # temperature
    rate = gamma1 * (n_th + 1)
    if rate > 0.0: c_op_list.append(sqrt(rate) * sm)
    rate = gamma1 * n_th
    if rate > 0.0: c_op_list.append(sqrt(rate) * sm.dag())
    rate = gamma2
    if rate > 0.0: c_op_list.append(sqrt(rate) * sz)

    # evolve and calculate expectation values
    output = mesolve(H, psi0, tlist, c_op_list, [sx, sy, sz])
    return output.expect[0], output.expect[1], output.expect[2]

## calculate the dynamics
w     = 1.0 * 2 * pi   # qubit angular frequency
theta = 0.2 * pi       # qubit angle from sigma_z axis (toward sigma_x axis)
gamma1 = 0.5      # qubit relaxation rate
gamma2 = 0.2      # qubit dephasing rate
# initial state
a = 1.0
psi0 = (a* basis(2,0) + (1-a)*basis(2,1))/(sqrt(a**2 + (1-a)**2))
tlist = linspace(0,4,250)
#expectation values for ploting
sx, sy, sz = qubit_integrate(w, theta, gamma1, gamma2, psi0, tlist)

b = Bloch()
b.vector_color = ['r']
b.view = [-40,30]
print 'len(sx) is ', len(sx)
for i in range(len(sx)):
    b.clear()
    b.add_vectors([np.sin(theta),0,np.cos(theta)])
    b.add_points([sx[:i+1],sy[:i+1],sz[:i+1]])
    b.save(dirc='temp') #saving images to temp directory in current working directory
```

**Comment by tilek** [comment]
I found a workaround for this. Instead of using b.clear() I moved bloch instantiation inside the loop that puts frames of the animation together and I had to give a different file name myself every time.

```
for i in range(len(sx)):
    b = Bloch()
    b.vector_color = ['r']
    b.view = [-40,30]
    b.add_vectors([np.sin(theta),0,np.cos(theta)])
    b.add_points([sx[:i+1],sy[:i+1],sz[:i+1]])
    b.save('%04d' % i, dirc='bloch_animation_images') #saving images to temp directory in current working directory
```

**Comment by nathanshammah** [comment]
I don't get any error in both cases. 
What is your `qutip.about()` message? 
By the way, QuTiP does not support anymore Python 2.7, see #882. 
My specifications are
```
QuTiP Version:      4.3.1
Numpy Version:      1.16.2
Scipy Version:      1.2.1
Cython Version:     0.28.5
Matplotlib Version: 2.2.3
Python Version:     3.6.7
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Darwin (x86_64)
```
