### ISSUE TITLE
Platen solver for ssesolve does not work.

### ISSUE THREAD

**Issue by paulsbrookes** [qutip/qutip#857]
Hi. I've been trying to use the Platen solver for ssesolve but it doesn't seem to work. Running the code below produces an error.

 Here's the code:
```
from qutip import *
import numpy as np

N = 15
w0 = 1.0 * 2 * np.pi
A = 0.1 * 2 * np.pi
times = np.linspace(0, 1.5, 150)
gamma = 0.25

ntraj = 1
nsubsteps = 1

a = destroy(N)
x = a + a.dag()
y = -1.0j*(a - a.dag())

H = w0 * a.dag() * a + A * (a + a.dag())

rho0 = coherent(N, np.sqrt(5.0), method='analytic')
c_ops = [np.sqrt(gamma) * a]
e_ops = [a.dag() * a, x, y]

result = ssesolve(H, rho0, times, [np.sqrt(gamma) * a], e_ops, ntraj=ntraj, nsubsteps=nsubsteps, method='homodyne', map_func=parallel_map, solver='platen')
```

Here's the error:
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    result = ssesolve(H, rho0, times, [np.sqrt(gamma) * a], e_ops, ntraj=ntraj, nsubsteps=nsubsteps, method='homodyne', map_func=parallel_map, solver='platen')
  File "/home/paul/anaconda3/envs/bistable/lib/python2.7/site-packages/qutip/stochastic.py", line 377, in ssesolve
    res = _ssesolve_generic(sso, sso.options, sso.progress_bar)
  File "/home/paul/anaconda3/envs/bistable/lib/python2.7/site-packages/qutip/stochastic.py", line 758, in _ssesolve_generic
    task_args, task_kwargs, **map_kwargs)
  File "/home/paul/anaconda3/envs/bistable/lib/python2.7/site-packages/qutip/parallel.py", line 183, in serial_map
    result = task(value, *task_args, **task_kwargs)
  File "/home/paul/anaconda3/envs/bistable/lib/python2.7/site-packages/qutip/stochastic.py", line 859, in _ssesolve_single_trajectory
    A_ops, dt, dW[:, t_idx, j, :], d1, d2, sso.args)
  File "/home/paul/anaconda3/envs/bistable/lib/python2.7/site-packages/qutip/stochastic.py", line 1843, in _rhs_psi_platen
    d1(A, psi_t) * dt +
TypeError: d1_psi_homodyne() takes exactly 4 arguments (2 given)

```
I've rewritten the _rhs_psi_platen function to fix this issue. Would you like me to make a pull request?
~

**Comment by nathanshammah** [comment]
Solved in QuTiP 4.4.0 release. See [`ssesolve` new methods](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-ssesolver-new-methods.ipynb) and [benchmarks](https://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/development/development-ssesolve-tests.ipynb) for details. I checked that your snippet now runs.
