### ISSUE TITLE
Tests failing (possibly) due to scipy Deprecation in power-gmres solver

### ISSUE THREAD

**Issue by sahmed95** [qutip/qutip#862]
I can't quite figure out if this is simply due to the DeprecationWarnings or something else but all tests are failing due to `atol` not being set for the gmres solver. I will try to set `atol` and check if the tests pass.

Error log: https://api.travis-ci.org/v3/job/379109482/log.txt.
```
scipy/sparse/linalg/isolve/iterative.py:2: DeprecationWarning: scipy.sparse.linalg.bicgstab called without specifying `atol`. The default value will be changed in a future release. For compatibility, specify a value for `atol` explicitly, e.g., ``bicgstab(..., atol=0)``, or to retain the old behavior ``bicgstab(..., atol='legacy')``


```

```
..................................................
======================================================================
ERROR: Steady state: Thermal qubit - power-gmres solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/shahnawaz/dev/qutip/qutip/tests/test_steadystate.py", line 145, in test_qubit_power_gmres
    rho_ss = steadystate(H, c_op_list, method='power-gmres')
  File "/Users/shahnawaz/dev/qutip/qutip/steadystate.py", line 298, in steadystate
    return _steadystate_power(A, ss_args)
  File "/Users/shahnawaz/dev/qutip/qutip/steadystate.py", line 863, in _steadystate_power
    v = v / la.norm(v, np.inf)
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/scipy/linalg/misc.py", line 137, in norm
    a = np.asarray_chkfinite(a)
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

----------------------------------------------------------------------
Ran 561 tests in 576.175s

FAILED (SKIP=19, errors=1)
```

**Comment by ajgpitch** [comment]
Attempted fix in #870

**Comment by ajgpitch** [comment]
On investigation and reflection I would say that the issue here is that `gmres` in scipy 1.1 returns an array of `NaN` when it fails to converge. It should return the (outside tol) solution, as it had done previously.

I will raise this with scipy

**Comment by ajgpitch** [comment]
Somehow I cannot recreate the NaN issue today. I have no idea why. I am just gonna drop it and move on
