### ISSUE TITLE
Tests fail: No module named spmatfuncs

### ISSUE THREAD

**Issue by yurivict** [qutip/qutip#891]
Running this code
```
import qutip.testing as qt
qt.run()
```
produces an error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "qutip/__init__.py", line 171, in <module>
    from qutip.qobj import *
  File "qutip/qobj.py", line 60, in <module>
    from qutip.fastsparse import fast_csr_matrix, fast_identity
  File "qutip/fastsparse.py", line 406, in <module>
    from qutip.cy.spmath import (zcsr_transpose, zcsr_adjoint, zcsr_mult)
  File "qutip/cy/__init__.py", line 1, in <module>
    from qutip.cy.spmatfuncs import *
ImportError: No module named spmatfuncs
```

**Comment by sahmed95** [comment]
How did you install QuTiP? I installed a fresh copy with conda and I do have spmatfuncs.
Are you building from source?

```
shahnawaz@torch:~/dev$ conda install qutip
Solving environment: done

## Package Plan ##

  environment location: /home/shahnawaz/miniconda3

  added / updated specs:
    - qutip


The following NEW packages will be INSTALLED:

    qutip: 4.2.0-np113py36_2 conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
shahnawaz@torch:~/dev$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qutip.cy.spmatfuncs import *
>>>
```

**Comment by yurivict** [comment]
> How did you install QuTiP?

In the FreeBSD, after QuTiP has been built, I run ```python -c "import qutip.testing as qt; qt.run();"```, and it fails.

**Comment by yurivict** [comment]
Once installed, running
```
import qutip.testing as qt
qt.run()
```

fails:
```
Python Version:     2.7.15
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    qt.run()
  File "/usr/local/lib/python2.7/site-packages/qutip/testing.py", line 40, in run
    about()
  File "/usr/local/lib/python2.7/site-packages/qutip/about.py", line 77, in about
    print("Number of CPUs:     %s" % hardware_info()['cpus'])
KeyError: 'cpus'
```

**Comment by yurivict** [comment]
The last error is fixed by this PR: https://github.com/qutip/qutip/pull/895

The first error (missing spmatfuncs) is still there.

**Comment by ajgpitch** [comment]
The first error generally occurs if you are running qutip from within the directory where you installed it

**Comment by yurivict** [comment]
Ok, thanks, I made it to run in the port by supplying ```PYTHONPATH``` to the build directory.

**Comment by nathanshammah** [comment]
This  issue could be closed if all is fixed.
