### ISSUE TITLE
Error with conda MKL2019.0 on Windows

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip#975]
This was reported on the help group
https://groups.google.com/forum/#!topic/qutip/L-MIFFwK0xU

(copying from there)
the newest mkl(Math library for intel) version(2019) can not work on QuTiP 4.3.1. I rollback it to mkl(2018.0.3), the qutip.testing then work well.

If using mkl(2019.0), there will MKL read problems, like:
```
  File "C:\Users\ym24chen\Anaconda3\
    x = lu.solve(b, verbose=verbose)
  File "C:\Users\ym24chen\Anaconda3\envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 164, in solve
    np_x, np_error)
OSError: exception: access violation reading 0x0000000000000008
envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 384, in mkl_spsolve
```

Env info:
```
QuTiP Version:      4.3.1
Numpy Version:      1.15.4
Scipy Version:      1.1.0
Cython Version:     0.29.6
Matplotlib Version: 3.0.3
Python Version:     3.7.2
Number of CPUs:     8
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\canwa\AppData\Local\conda\conda\envs\qutipenv\lib\site-packages\qutip
==============================================================================
```

**Comment by ajgpitch** [comment]
Can anyone repeat this?

**Comment by BoxiLi** [comment]
Yes, I have seen similar errors on my windows when running the tests. Looks like memory error
```
======================================================================
ERROR: Counting statistics: current and current noise in a DQD model
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Boxi\Miniconda3\envs\qutip-dev-py3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\tests\test_countstat.py", line 73, in test_dqd_current
    rhoss = steadystate(L)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\steadystate.py", line 290, in steadystate
    return _steadystate_direct_sparse(A, ss_args)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\steadystate.py", line 460, in _steadystate_direct_sparse
    weighted_matching=ss_args['weighted_matching'])
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\_mkl\spsolve.py", line 393, in mkl_spsolve
    x = lu.solve(b, verbose=verbose)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\_mkl\spsolve.py", line 170, in solve
    np_x, np_error)
OSError: exception: access violation reading 0x0000000099EC80F8

======================================================================
ERROR: MKL spsolve : Hermitian (real) solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Boxi\Miniconda3\envs\qutip-dev-py3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\tests\test_mkl.py", line 230, in test_mkl_spsolve10
    y = mkl_spsolve(A, b, hermitian=1)
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\_mkl\spsolve.py", line 414, in mkl_spsolve
    lu.delete()
  File "C:\Users\Boxi\OneDrive\Studium\qutip-project\qutip\qutip\_mkl\spsolve.py", line 208, in delete
    byref(c_int(0)), np_error)
OSError: exception: access violation reading 0x00000006FFFFFFEF

======================================================================
```
Enviroment:
```
QuTiP Version:      4.4.0.dev0+73a27971
Numpy Version:      1.16.2
Scipy Version:      1.2.1
Cython Version:     0.29.6
Matplotlib Version: 3.0.3
Python Version:     3.7.3
Number of CPUs:     12
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\Boxi\Miniconda3\envs\qutip-dev-py3\lib\site-packages\qutip-4.4.0.dev0+73a27971-py3.7-win-amd64.egg\qutip
```

**Comment by denisvion** [comment]
Hi, I also have the problem on both windows 64 bit  7 and 10, with with miniconda 64 bits 2019.07 and qutip 4.4, after following exactly the official install reciepe from http://qutip.org/docs/latest/installation.html
And replacing the last MKL by MKL2018 does not fix the problem for me.
Any more robust solution?

**Comment by zhedie** [comment]
> This was reported on the help group
> https://groups.google.com/forum/#!topic/qutip/L-MIFFwK0xU
> 
> (copying from there)
> the newest mkl(Math library for intel) version(2019) can not work on QuTiP 4.3.1. I rollback it to mkl(2018.0.3), the qutip.testing then work well.
> 
> If using mkl(2019.0), there will MKL read problems, like:
> 
> ```
>   File "C:\Users\ym24chen\Anaconda3\
>     x = lu.solve(b, verbose=verbose)
>   File "C:\Users\ym24chen\Anaconda3\envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 164, in solve
>     np_x, np_error)
> OSError: exception: access violation reading 0x0000000000000008
> envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 384, in mkl_spsolve
> ```
> 
> Env info:
> 
> ```
> QuTiP Version:      4.3.1
> Numpy Version:      1.15.4
> Scipy Version:      1.1.0
> Cython Version:     0.29.6
> Matplotlib Version: 3.0.3
> Python Version:     3.7.2
> Number of CPUs:     8
> BLAS Info:          INTEL MKL
> OPENMP Installed:   False
> INTEL MKL Ext:      True
> Platform Info:      Windows (AMD64)
> Installation path:  C:\Users\canwa\AppData\Local\conda\conda\envs\qutipenv\lib\site-packages\qutip
> ==============================================================================
> ```

How can I  rollback it to mkl(2018.0.3)? I just use "conda install mkl=2018" but the test still return errors.

**Comment by denisvion** [comment]
Same for me :
I rolled back to previous mkl and qutip by running:
conda install mkl=2018.0.3
conda install qutip=4.1.3

Now my programs calling steadystate work again but I also get 1 error related to mkl and steady when running  the full test.

Denis

De : zhang [mailto:notifications@github.com]
Envoyé : samedi 28 septembre 2019 09:33
À : qutip/qutip <qutip@noreply.github.com>
Cc : VION Denis <denis.vion@cea.fr>; Comment <comment@noreply.github.com>
Objet : Re: [qutip/qutip] Error with conda MKL2019.0 on Windows (#975)


This was reported on the help group
https://groups.google.com/forum/#!topic/qutip/L-MIFFwK0xU

(copying from there)
the newest mkl(Math library for intel) version(2019) can not work on QuTiP 4.3.1. I rollback it to mkl(2018.0.3), the qutip.testing then work well.

If using mkl(2019.0), there will MKL read problems, like:

  File "C:\Users\ym24chen\Anaconda3\

    x = lu.solve(b, verbose=verbose)

  File "C:\Users\ym24chen\Anaconda3\envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 164, in solve

    np_x, np_error)

OSError: exception: access violation reading 0x0000000000000008

envs\qutip-env\lib\site-packages\qutip\_mkl\spsolve.py", line 384, in mkl_spsolve

Env info:

QuTiP Version:      4.3.1

Numpy Version:      1.15.4

Scipy Version:      1.1.0

Cython Version:     0.29.6

Matplotlib Version: 3.0.3

Python Version:     3.7.2

Number of CPUs:     8

BLAS Info:          INTEL MKL

OPENMP Installed:   False

INTEL MKL Ext:      True

Platform Info:      Windows (AMD64)

Installation path:  C:\Users\canwa\AppData\Local\conda\conda\envs\qutipenv\lib\site-packages\qutip

==============================================================================

How can I rollback it to mkl(2018.0.3)? I just use "conda install mkl=2018" but the test still return errors.

**Comment by zhedie** [comment]
I met the same errors as you described.

**Comment by mgely** [comment]
I also have this same issue, even after re-installing Anaconda3 and qutip from scratch.
Rolling back to mkl=2018.0.3 did not help.

Here is my setup (I'm using Windows 7):
-------
QuTiP Version:      4.4.1
Numpy Version:      1.16.5
Scipy Version:      1.3.1
Cython Version:     0.29.13
Matplotlib Version: 3.1.1
Python Version:     3.7.3
Number of CPUs:     2
BLAS Info:          INTEL MKL
OPENMP Installed:   False
INTEL MKL Ext:      True
Platform Info:      Windows (AMD64)

**Comment by Ericgig** [comment]
Quite a few mkl version have been released and Qutip's use of them has changed a lot since then. Probably no longer relevant...
